export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
                <header> Main  header </header>
                {children}
                <footer>Main footer</footer>
            </body>
    </html>
  )
}
